// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: KartDataDisplay

#ifndef _KARTDATADISPLAY_UI_H
#define _KARTDATADISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_images_bg_png);   // assets/Images/bg.png
LV_IMG_DECLARE( ui_img_1963053285);   // assets/Images/Anim/speed-01.png
LV_IMG_DECLARE( ui_img_1963050210);   // assets/Images/Anim/speed-02.png
LV_IMG_DECLARE( ui_img_1963051235);   // assets/Images/Anim/speed-03.png
LV_IMG_DECLARE( ui_img_1963047912);   // assets/Images/Anim/speed-04.png
LV_IMG_DECLARE( ui_img_1963048937);   // assets/Images/Anim/speed-05.png
LV_IMG_DECLARE( ui_img_1963045862);   // assets/Images/Anim/speed-06.png
LV_IMG_DECLARE( ui_img_1963046887);   // assets/Images/Anim/speed-07.png
LV_IMG_DECLARE( ui_img_1963060972);   // assets/Images/Anim/speed-08.png
LV_IMG_DECLARE( ui_img_1963061997);   // assets/Images/Anim/speed-09.png
LV_IMG_DECLARE( ui_img_1524054327);   // assets/Images/Anim/speed-10.png
LV_IMG_DECLARE( ui_img_images_center_red_png);   // assets/Images/center_red.png
LV_IMG_DECLARE( ui_img_images_center_yellow_png);   // assets/Images/center_yellow.png
LV_IMG_DECLARE( ui_img_images_center_green_png);   // assets/Images/center_green.png
LV_IMG_DECLARE( ui_img_images_cl_red_png);   // assets/Images/cl_red.png
LV_IMG_DECLARE( ui_img_images_cl_yellow_png);   // assets/Images/cl_yellow.png
LV_IMG_DECLARE( ui_img_images_cl_green_png);   // assets/Images/cl_green.png
LV_IMG_DECLARE( ui_img_images_cr_red_png);   // assets/Images/cr_red.png
LV_IMG_DECLARE( ui_img_images_cr_yellow_png);   // assets/Images/cr_yellow.png
LV_IMG_DECLARE( ui_img_images_cr_green_png);   // assets/Images/cr_green.png
LV_IMG_DECLARE( ui_img_images_left_red_png);   // assets/Images/left_red.png
LV_IMG_DECLARE( ui_img_images_g1_png);   // assets/Images/g1.png
LV_IMG_DECLARE( ui_img_images_g2_png);   // assets/Images/g2.png
LV_IMG_DECLARE( ui_img_images_g3_png);   // assets/Images/g3.png
LV_IMG_DECLARE( ui_img_images_g4_png);   // assets/Images/g4.png
LV_IMG_DECLARE( ui_img_images_g5_png);   // assets/Images/g5.png
LV_IMG_DECLARE( ui_img_images_g6_png);   // assets/Images/g6.png
LV_IMG_DECLARE( ui_img_images_g7_png);   // assets/Images/g7.png
LV_IMG_DECLARE( ui_img_images_g8_png);   // assets/Images/g8.png
LV_IMG_DECLARE( ui_img_images_g9_png);   // assets/Images/g9.png
LV_IMG_DECLARE( ui_img_images_g10_png);   // assets/Images/g10.png
LV_IMG_DECLARE( ui_img_images_g11_png);   // assets/Images/g11.png
LV_IMG_DECLARE( ui_img_images_g12_png);   // assets/Images/g12.png
LV_IMG_DECLARE( ui_img_images_g13_png);   // assets/Images/g13.png
LV_IMG_DECLARE( ui_img_images_g14_png);   // assets/Images/g14.png
LV_IMG_DECLARE( ui_img_images_g15_png);   // assets/Images/g15.png
LV_IMG_DECLARE( ui_img_images_g16_png);   // assets/Images/g16.png
LV_IMG_DECLARE( ui_img_images_g17_png);   // assets/Images/g17.png
LV_IMG_DECLARE( ui_img_images_g18_png);   // assets/Images/g18.png
LV_IMG_DECLARE( ui_img_images_g19_png);   // assets/Images/g19.png
LV_IMG_DECLARE( ui_img_images_g20_png);   // assets/Images/g20.png
LV_IMG_DECLARE( ui_img_images_needle_png);   // assets/Images/needle.png

// FONTS
LV_FONT_DECLARE( ui_font_DS18);
LV_FONT_DECLARE( ui_font_DS36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
