// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#ifndef _MINIMALIST_UI_H
#define _MINIMALIST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_dashboardscreen.h"
#include "screens/ui_configscreen.h"
#include "screens/ui_statusbarscreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_BarlowCondensedBold200);
LV_FONT_DECLARE( ui_font_BarlowCondensedBold60);
LV_FONT_DECLARE( ui_font_BarlowCondensedBold48);
LV_FONT_DECLARE( ui_font_BarlowCondensedBold32);
LV_FONT_DECLARE( ui_font_BarlowCondensedBold22);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
