// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: KartDataDisplay

#ifndef _KARTDATADISPLAY_UI_H
#define _KARTDATADISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_images_bg_png);   // assets/Images/bg.png
LV_IMG_DECLARE( ui_img_1963053285);   // assets/Images/Anim/speed-01.png
LV_IMG_DECLARE( ui_img_1963050210);   // assets/Images/Anim/speed-02.png
LV_IMG_DECLARE( ui_img_1963051235);   // assets/Images/Anim/speed-03.png
LV_IMG_DECLARE( ui_img_1963047912);   // assets/Images/Anim/speed-04.png
LV_IMG_DECLARE( ui_img_1963048937);   // assets/Images/Anim/speed-05.png
LV_IMG_DECLARE( ui_img_1963045862);   // assets/Images/Anim/speed-06.png
LV_IMG_DECLARE( ui_img_1963046887);   // assets/Images/Anim/speed-07.png
LV_IMG_DECLARE( ui_img_1963060972);   // assets/Images/Anim/speed-08.png
LV_IMG_DECLARE( ui_img_1963061997);   // assets/Images/Anim/speed-09.png
LV_IMG_DECLARE( ui_img_1524054327);   // assets/Images/Anim/speed-10.png
LV_IMG_DECLARE( ui_img_images_needle_png);   // assets/Images/needle.png

// FONTS
LV_FONT_DECLARE( ui_font_DS36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
