// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

// After SquareLine regeneration, re-add: #include "ui_theme.h"
// and restore the two delegate calls below.

#include "ui.h"
#include "ui_theme.h"

void applyDarkTheme(lv_event_t * e)
{
	ui_theme_apply_dark(e);
}

void applyLightTheme(lv_event_t * e)
{
	ui_theme_apply_light(e);
}

void stopRecording(lv_event_t * e)
{
	ui_session_stop(e);
}

void sessionClicked(lv_event_t * e)
{
	ui_session_clicked(e);
}

void previousTrackClicked(lv_event_t * e)
{
	ui_track_prev(e);
}

void nextTrackClicked(lv_event_t * e)
{
	ui_track_next(e);
}

void startPinLClicked(lv_event_t * e)
{
	ui_track_pin_l(e);
}

void startPinRClicked(lv_event_t * e)
{
	ui_track_pin_r(e);
}

void cancelClicked(lv_event_t * e)
{
	ui_track_cancel(e);
}

void saveClicked(lv_event_t * e)
{
	ui_track_save(e);
}

void addTrackClicked(lv_event_t * e)
{
	ui_track_add(e);
}

void latLClicked(lv_event_t * e)
{
	ui_track_edit_lat_l(e);
}

void lonLClicked(lv_event_t * e)
{
	ui_track_edit_lon_l(e);
}

void emptyLClicked(lv_event_t * e)
{
	ui_track_edit_lat_l(e);
}

void latRClicked(lv_event_t * e)
{
	ui_track_edit_lat_r(e);
}

void lonRClicked(lv_event_t * e)
{
	ui_track_edit_lon_r(e);
}

void emptyRClicked(lv_event_t * e)
{
	ui_track_edit_lat_r(e);
}

void trackNameClicked(lv_event_t * e)
{
	ui_track_edit_track_name(e);
}
