// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#include "ui.h"

void applyDarkTheme(lv_event_t * e)
{
	// Your code here
}

void applyLightTheme(lv_event_t * e)
{
	// Your code here
}
