// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void stopRecording(lv_event_t * e);
void sessionClicked(lv_event_t * e);
void applyDarkTheme(lv_event_t * e);
void applyLightTheme(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
