// NOT generated by SquareLine Studio — safe to edit.
#include "ui_theme.h"
#include "ConfigManager.h"

// Narrow C bridge to uiHelper.setTheme(), defined in uiHelper.cpp.
// Avoids pulling in the full uiHelper.h header (which needs DisplayBSP headers
// that are not in the include path for lib/ui).
extern "C" void ui_helper_set_theme(int mode);

void ui_theme_apply_dark(lv_event_t *) {
    configManager.setTheme(0);
    configManager.save();
    ui_helper_set_theme(0);
}

void ui_theme_apply_light(lv_event_t *) {
    configManager.setTheme(1);
    configManager.save();
    ui_helper_set_theme(1);
}
