// NOT generated by SquareLine Studio — safe to edit.
// If ui_events.c is regenerated, restore: #include "ui_theme.h"
// and the two one-line delegate calls inside applyDarkTheme / applyLightTheme.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"
void ui_theme_apply_dark(lv_event_t *e);
void ui_theme_apply_light(lv_event_t *e);
void ui_session_clicked(lv_event_t *e);   /* toggle start / stop */
void ui_session_stop(lv_event_t *e);      /* stop only (from PanelRecording) */
#ifdef __cplusplus
}
#endif
