// NOT generated by SquareLine Studio
// If ui_events.c is regenerated, restore: #include "ui_theme.h"
// and the two one-line delegate calls inside applyDarkTheme / applyLightTheme.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"
void ui_theme_apply_dark(lv_event_t *e);
void ui_theme_apply_light(lv_event_t *e);
void ui_session_clicked(lv_event_t *e);   /* toggle start / stop */
void ui_session_stop(lv_event_t *e);      /* stop only (from PanelRecording) */
void ui_track_prev(lv_event_t *e);        /* navigate to previous track */
void ui_track_next(lv_event_t *e);        /* navigate to next track */
void ui_track_cancel(lv_event_t *e);      /* discard pending changes */
void ui_track_save(lv_event_t *e);        /* persist selection + update LapManager */
void ui_track_pin_l(lv_event_t *e);       /* pin or reset the left start-line point */
void ui_track_pin_r(lv_event_t *e);       /* pin or reset the right start-line point */
void ui_track_add(lv_event_t *e);         /* append a new empty track */
void ui_track_edit_track_name(lv_event_t *e);
void ui_track_edit_lat_l(lv_event_t *e);
void ui_track_edit_lon_l(lv_event_t *e);
void ui_track_edit_lat_r(lv_event_t *e);
void ui_track_edit_lon_r(lv_event_t *e);
#ifdef __cplusplus
}
#endif
