// NOT generated by SquareLine Studio — safe to edit.
#include "ui_theme.h"
#include "ui.h"
#include "ConfigManager.h"

// Narrow C bridges — avoid pulling in full headers with DisplayBSP dependencies.
// Implemented in uiHelper.cpp and main_display.cpp respectively.
extern "C" void ui_helper_set_theme(int mode);
extern "C" void ui_helper_toggle_session();
extern "C" void ui_helper_stop_session();

extern "C" int  ui_helper_get_track_idx();
extern "C" void ui_helper_set_track_idx(int i);
extern "C" void ui_helper_set_start_l(double lat, double lon, bool valid);
extern "C" void ui_helper_set_start_r(double lat, double lon, bool valid);
extern "C" void ui_helper_set_dirty(bool d);
extern "C" void ui_helper_apply_finish_line(double ll, double ln, double rl, double rn);
extern "C" bool ui_helper_get_gps(double *lat, double *lon);

void ui_theme_apply_dark(lv_event_t *) {
    configManager.setTheme(0);
    configManager.save();
    ui_helper_set_theme(0);
}

void ui_theme_apply_light(lv_event_t *) {
    configManager.setTheme(1);
    configManager.save();
    ui_helper_set_theme(1);
}

// ============================================================================
// SESSION COUNTDOWN OVERLAY
// ============================================================================

static lv_timer_t *s_countdown_timer = nullptr;
static lv_obj_t   *s_overlay        = nullptr;
static lv_obj_t   *s_count_label    = nullptr;
static int         s_ticks_left     = 0;

static void countdown_destroy() {
    if (s_countdown_timer) {
        lv_timer_delete(s_countdown_timer);
        s_countdown_timer = nullptr;
    }
    if (s_overlay) {
        lv_obj_delete(s_overlay);
        s_overlay     = nullptr;
        s_count_label = nullptr;
    }
}

static void countdown_tick_cb(lv_timer_t *) {
    s_ticks_left--;
    if (s_ticks_left > 0) {
        char buf[4];
        lv_snprintf(buf, sizeof(buf), "%d", s_ticks_left);
        lv_label_set_text(s_count_label, buf);
    } else {
        // repeat_count exhausted — LVGL auto-deletes the timer after this callback
        s_countdown_timer = nullptr;
        if (s_overlay) {
            lv_obj_delete(s_overlay);
            s_overlay     = nullptr;
            s_count_label = nullptr;
        }
        ui_helper_toggle_session();
        _ui_screen_change(&ui_dashboardscreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0,
                          &ui_dashboardscreen_screen_init);
    }
}

void ui_session_clicked(lv_event_t *) {
    if (s_overlay) return;

    int idx = (int)configManager.getSelectedTrack();
    const TrackConfig *tc = configManager.getTrack(idx);
    const char *track_name = (tc && tc->name[0]) ? tc->name : "—";

    // Full-screen semi-opaque overlay parented to the config screen
    s_overlay = lv_obj_create(ui_configscreen);
    lv_obj_set_size(s_overlay, 480, 320);
    lv_obj_set_pos(s_overlay, 0, 0);
    lv_obj_remove_flag(s_overlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(s_overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(s_overlay, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(s_overlay, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(s_overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(s_overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Track name
    lv_obj_t *name_lbl = lv_label_create(s_overlay);
    lv_obj_set_width(name_lbl, 440);
    lv_label_set_long_mode(name_lbl, LV_LABEL_LONG_DOT);
    lv_label_set_text(name_lbl, track_name);
    lv_obj_set_align(name_lbl, LV_ALIGN_CENTER);
    lv_obj_set_y(name_lbl, -50);
    lv_obj_set_style_text_align(name_lbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(name_lbl, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(name_lbl, &ui_font_BarlowCondensedBold48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(name_lbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Countdown digit
    s_count_label = lv_label_create(s_overlay);
    lv_label_set_text(s_count_label, "3");
    lv_obj_set_align(s_count_label, LV_ALIGN_CENTER);
    lv_obj_set_y(s_count_label, 20);
    lv_obj_set_style_text_color(s_count_label, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_count_label, &ui_font_BarlowCondensedBold60, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Cancel button
    lv_obj_t *cancel_btn = lv_button_create(s_overlay);
    lv_obj_set_size(cancel_btn, 130, 40);
    lv_obj_set_align(cancel_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(cancel_btn, -24);
    lv_obj_remove_flag(cancel_btn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(cancel_btn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cancel_btn, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cancel_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cancel_btn, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cancel_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cancel_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(cancel_btn,
        [](lv_event_t *e) {
            if (lv_event_get_code(e) == LV_EVENT_CLICKED) countdown_destroy();
        },
        LV_EVENT_ALL, nullptr);

    lv_obj_t *cancel_lbl = lv_label_create(cancel_btn);
    lv_label_set_text(cancel_lbl, "CANCEL");
    lv_obj_set_align(cancel_lbl, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(cancel_lbl, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cancel_lbl, &ui_font_BarlowCondensedBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_ticks_left = 3;
    s_countdown_timer = lv_timer_create(countdown_tick_cb, 1000, nullptr);
    lv_timer_set_repeat_count(s_countdown_timer, 3);
}

void ui_session_stop(lv_event_t *) {
    ui_helper_stop_session();
}

// ============================================================================
// TRACK SETUP (called from ui_events.c via ui_theme.h declarations)
// ============================================================================

static void apply_track_coords(int idx) {
    const TrackConfig *tc = configManager.getTrack(idx);
    if (!tc) {
        ui_helper_set_start_l(0.0, 0.0, false);
        ui_helper_set_start_r(0.0, 0.0, false);
        return;
    }
    ui_helper_set_start_l(tc->left_lat,  tc->left_lon,  tc->left_valid);
    ui_helper_set_start_r(tc->right_lat, tc->right_lon, tc->right_valid);
}

void ui_track_prev(lv_event_t *) {
    int n = configManager.getTrackCount();
    if (n == 0) return;
    int idx = (ui_helper_get_track_idx() - 1 + n) % n;
    ui_helper_set_track_idx(idx);
    apply_track_coords(idx);
    ui_helper_set_dirty(true);
}

void ui_track_next(lv_event_t *) {
    int n = configManager.getTrackCount();
    if (n == 0) return;
    int idx = (ui_helper_get_track_idx() + 1) % n;
    ui_helper_set_track_idx(idx);
    apply_track_coords(idx);
    ui_helper_set_dirty(true);
}

void ui_track_cancel(lv_event_t *) {
    configManager.reloadTracks();
    int saved = (int)configManager.getSelectedTrack();
    ui_helper_set_track_idx(saved);
    apply_track_coords(saved);
    ui_helper_set_dirty(false);
}

void ui_track_save(lv_event_t *) {
    int idx = ui_helper_get_track_idx();
    configManager.setSelectedTrack((uint8_t)idx);
    configManager.save();
    configManager.saveTracks();

    const TrackConfig *tc = configManager.getTrack(idx);
    if (tc && tc->left_valid && tc->right_valid) {
        ui_helper_apply_finish_line(tc->left_lat, tc->left_lon,
                                    tc->right_lat, tc->right_lon);
    }

    ui_helper_set_dirty(false);
}

// ============================================================================
// PIN / RESET (capture or clear the current GPS position for a start-line side)
// ============================================================================

static void pin_side(bool left) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *existing = configManager.getTrack(idx);
    if (!existing) return;

    TrackConfig tc = *existing;
    bool currently_valid = left ? tc.left_valid : tc.right_valid;

    if (currently_valid) {
        // RESET: clear this side's pin
        if (left) { tc.left_lat  = 0.0; tc.left_lon  = 0.0; tc.left_valid  = false; }
        else      { tc.right_lat = 0.0; tc.right_lon = 0.0; tc.right_valid = false; }
    } else {
        // PIN: capture GPS — bail silently if no fix
        double lat, lon;
        if (!ui_helper_get_gps(&lat, &lon)) return;
        if (left) { tc.left_lat  = lat; tc.left_lon  = lon; tc.left_valid  = true; }
        else      { tc.right_lat = lat; tc.right_lon = lon; tc.right_valid = true; }
    }

    configManager.setTrack(idx, tc);

    if (left) ui_helper_set_start_l(tc.left_lat,  tc.left_lon,  tc.left_valid);
    else      ui_helper_set_start_r(tc.right_lat, tc.right_lon, tc.right_valid);

    ui_helper_set_dirty(true);
}

void ui_track_pin_l(lv_event_t *) { pin_side(true); }
void ui_track_pin_r(lv_event_t *) { pin_side(false); }

// ============================================================================
// TRACK NAME POINTER ARRAY (keeps pointers into configManager for UiHelper)
// ============================================================================

extern "C" void ui_helper_set_track_names(const char *const *names, int n);

static const char *s_track_name_ptrs[CONFIG_MAX_TRACKS];

static void reload_tracks_display() {
    int n = configManager.getTrackCount();
    for (int i = 0; i < n; i++) {
        const TrackConfig *tc = configManager.getTrack(i);
        s_track_name_ptrs[i] = tc ? tc->name : "";
    }
    ui_helper_set_track_names(s_track_name_ptrs, n);
}

// ============================================================================
// INLINE KEYBOARD OVERLAY
// ============================================================================

using KbApply = void(*)(const char *);

static lv_obj_t *s_kb_overlay  = nullptr;
static lv_obj_t *s_kb_textarea = nullptr;
static KbApply   s_kb_apply    = nullptr;

static void kb_destroy() {
    if (s_kb_overlay) {
        lv_obj_delete(s_kb_overlay);
        s_kb_overlay  = nullptr;
        s_kb_textarea = nullptr;
    }
    s_kb_apply = nullptr;
}

static void kb_event_cb(lv_event_t *e) {
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_READY) {
        const char *txt = s_kb_textarea ? lv_textarea_get_text(s_kb_textarea) : "";
        KbApply fn = s_kb_apply;
        kb_destroy();
        if (fn) fn(txt);
    } else if (code == LV_EVENT_CANCEL) {
        kb_destroy();
    }
}

static void open_keyboard(const char *title, const char *initial,
                           KbApply apply_cb, lv_keyboard_mode_t mode) {
    if (s_kb_overlay || !ui_trackscreen) return;

    s_kb_apply = apply_cb;

    s_kb_overlay = lv_obj_create(ui_trackscreen);
    lv_obj_set_size(s_kb_overlay, 480, 320);
    lv_obj_set_pos(s_kb_overlay, 0, 0);
    lv_obj_remove_flag(s_kb_overlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(s_kb_overlay, 0, 0);
    lv_obj_set_style_bg_color(s_kb_overlay, lv_color_hex(0x050608), 0);
    lv_obj_set_style_bg_opa(s_kb_overlay, 255, 0);
    lv_obj_set_style_border_width(s_kb_overlay, 0, 0);
    lv_obj_set_style_pad_all(s_kb_overlay, 0, 0);

    // Field label (below the status bar strip)
    lv_obj_t *title_lbl = lv_label_create(s_kb_overlay);
    lv_label_set_text(title_lbl, title);
    lv_obj_set_pos(title_lbl, 12, 30);
    lv_obj_set_style_text_color(title_lbl, lv_color_hex(0x6B7280), 0);
    lv_obj_set_style_text_font(title_lbl, &lv_font_montserrat_14, 0);

    // Single-line textarea
    s_kb_textarea = lv_textarea_create(s_kb_overlay);
    lv_obj_set_width(s_kb_textarea, 460);
    lv_obj_set_height(s_kb_textarea, 46);
    lv_obj_set_pos(s_kb_textarea, 10, 48);
    lv_textarea_set_one_line(s_kb_textarea, true);
    lv_textarea_set_text(s_kb_textarea, initial ? initial : "");
    lv_obj_set_style_bg_color(s_kb_textarea, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(s_kb_textarea, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(s_kb_textarea, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(s_kb_textarea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(s_kb_textarea, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(s_kb_textarea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Built-in keyboard docked at the bottom
    lv_obj_t *kb = lv_keyboard_create(s_kb_overlay);
    lv_obj_set_size(kb, 480, 200);
    lv_obj_align(kb, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_keyboard_set_mode(kb, mode);
    lv_keyboard_set_textarea(kb, s_kb_textarea);
    lv_obj_add_event_cb(kb, kb_event_cb, LV_EVENT_ALL, nullptr);
}

// ============================================================================
// ADD TRACK
// ============================================================================

void ui_track_add(lv_event_t *) {
    int n = configManager.getTrackCount();
    if (n >= CONFIG_MAX_TRACKS) return;
    TrackConfig tc = {};
    strncpy(tc.name, "NOT SET", sizeof(tc.name) - 1);
    configManager.setTrack(n, tc);
    reload_tracks_display();
    ui_helper_set_track_idx(n);
    ui_helper_set_start_l(0.0, 0.0, false);
    ui_helper_set_start_r(0.0, 0.0, false);
    ui_helper_set_dirty(true);
}

// ============================================================================
// TRACK NAME KEYBOARD
// ============================================================================

static void apply_name_cb(const char *text) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *existing = configManager.getTrack(idx);
    if (!existing) return;
    TrackConfig tc = *existing;
    strncpy(tc.name, text, sizeof(tc.name) - 1);
    tc.name[sizeof(tc.name) - 1] = '\0';
    configManager.setTrack(idx, tc);
    reload_tracks_display();
    ui_helper_set_dirty(true);
}

void ui_track_edit_track_name(lv_event_t *) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *tc = configManager.getTrack(idx);
    open_keyboard("TRACK NAME", tc ? tc->name : "",
                  apply_name_cb, LV_KEYBOARD_MODE_TEXT_UPPER);
}

// ============================================================================
// COORDINATE KEYBOARD
// ============================================================================

enum class CoordField : uint8_t { LAT_L, LON_L, LAT_R, LON_R };
static CoordField s_kb_coord_field;

static void apply_coord_cb(const char *text) {
    double val = atof(text);
    int idx = ui_helper_get_track_idx();
    const TrackConfig *existing = configManager.getTrack(idx);
    if (!existing) return;
    TrackConfig tc = *existing;
    switch (s_kb_coord_field) {
        case CoordField::LAT_L: tc.left_lat  = val; tc.left_valid  = true; break;
        case CoordField::LON_L: tc.left_lon  = val;                        break;
        case CoordField::LAT_R: tc.right_lat = val; tc.right_valid = true; break;
        case CoordField::LON_R: tc.right_lon = val;                        break;
    }
    configManager.setTrack(idx, tc);
    if (s_kb_coord_field == CoordField::LAT_L || s_kb_coord_field == CoordField::LON_L)
        ui_helper_set_start_l(tc.left_lat, tc.left_lon, tc.left_valid);
    else
        ui_helper_set_start_r(tc.right_lat, tc.right_lon, tc.right_valid);
    ui_helper_set_dirty(true);
}

static void open_coord_kb(const char *title, CoordField field,
                            double cur, bool has_val) {
    s_kb_coord_field = field;
    char buf[24] = "";
    if (has_val) snprintf(buf, sizeof(buf), "%.6f", cur);
    open_keyboard(title, buf, apply_coord_cb, LV_KEYBOARD_MODE_NUMBER);
}

void ui_track_edit_lat_l(lv_event_t *) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *tc = configManager.getTrack(idx);
    open_coord_kb("LEFT LATITUDE",  CoordField::LAT_L,
                  tc ? tc->left_lat  : 0.0, tc && tc->left_valid);
}
void ui_track_edit_lon_l(lv_event_t *) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *tc = configManager.getTrack(idx);
    open_coord_kb("LEFT LONGITUDE", CoordField::LON_L,
                  tc ? tc->left_lon  : 0.0, tc && tc->left_valid);
}
void ui_track_edit_lat_r(lv_event_t *) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *tc = configManager.getTrack(idx);
    open_coord_kb("RIGHT LATITUDE",  CoordField::LAT_R,
                  tc ? tc->right_lat : 0.0, tc && tc->right_valid);
}
void ui_track_edit_lon_r(lv_event_t *) {
    int idx = ui_helper_get_track_idx();
    const TrackConfig *tc = configManager.getTrack(idx);
    open_coord_kb("RIGHT LONGITUDE", CoordField::LON_R,
                  tc ? tc->right_lon : 0.0, tc && tc->right_valid);
}
