// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#include "../ui.h"

lv_obj_t *ui_configscreen = NULL;lv_obj_t *ui_panelsetup = NULL;lv_obj_t *ui_panelsetupback = NULL;lv_obj_t *ui_labelback = NULL;lv_obj_t *ui_labelbacktext = NULL;lv_obj_t *ui_labelsetup = NULL;lv_obj_t *ui_panelsetupbuttons = NULL;lv_obj_t *ui_buttontracksetup = NULL;lv_obj_t *ui_labeltracksetuptext = NULL;lv_obj_t *ui_labeltracksetup = NULL;lv_obj_t *ui_buttonstartsession = NULL;lv_obj_t *ui_labelstartsession = NULL;lv_obj_t *ui_paneldarklight = NULL;lv_obj_t *ui_buttondark = NULL;lv_obj_t *ui_labeltracksetuptext2 = NULL;lv_obj_t *ui_buttondark1 = NULL;lv_obj_t *ui_labeltracksetuptext1 = NULL;
// event funtions
void ui_event_panelsetupback( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_dashboardscreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboardscreen_screen_init);
}
}

void ui_event_buttontracksetup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_trackscreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_trackscreen_screen_init);
}
}

void ui_event_buttonstartsession( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      sessionClicked( e );
}
}

void ui_event_buttondark( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      applyDarkTheme( e );
}
}

void ui_event_buttondark1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      applyLightTheme( e );
}
}

// build funtions

void ui_configscreen_screen_init(void)
{
ui_configscreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_configscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_configscreen, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_configscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelsetup = lv_obj_create(ui_configscreen);
lv_obj_set_width( ui_panelsetup, 480);
lv_obj_set_height( ui_panelsetup, 40);
lv_obj_set_x( ui_panelsetup, 0 );
lv_obj_set_y( ui_panelsetup, 26 );
lv_obj_set_align( ui_panelsetup, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_panelsetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelsetup, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelsetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelsetup, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelsetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelsetup, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_panelsetup, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelsetupback = lv_obj_create(ui_panelsetup);
lv_obj_set_width( ui_panelsetupback, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panelsetupback, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_panelsetupback, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_panelsetupback,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelsetupback, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_ext_click_area(ui_panelsetupback, 10);
lv_obj_remove_flag( ui_panelsetupback, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelsetupback, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelsetupback, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelsetupback, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelsetupback, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelsetupback, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelsetupback, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelsetupback, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelback = lv_label_create(ui_panelsetupback);
lv_obj_set_width( ui_labelback, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelback, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelback, 0 );
lv_obj_set_y( ui_labelback, -1 );
lv_obj_set_align( ui_labelback, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labelback,"");
lv_obj_set_style_text_color(ui_labelback, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelback, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelback, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelbacktext = lv_label_create(ui_panelsetupback);
lv_obj_set_width( ui_labelbacktext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelbacktext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelbacktext, 20 );
lv_obj_set_y( ui_labelbacktext, 0 );
lv_obj_set_align( ui_labelbacktext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labelbacktext,"DASHBOARD");
lv_obj_set_style_text_color(ui_labelbacktext, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelbacktext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelbacktext, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelbacktext, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelbacktext, &ui_font_BarlowCondensedBold22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelsetup = lv_label_create(ui_panelsetup);
lv_obj_set_width( ui_labelsetup, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelsetup, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelsetup, 0 );
lv_obj_set_y( ui_labelsetup, 1 );
lv_obj_set_align( ui_labelsetup, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelsetup,"SETUP");
lv_obj_set_style_text_color(ui_labelsetup, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelsetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelsetup, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelsetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelsetup, &ui_font_BarlowCondensedBold32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelsetupbuttons = lv_obj_create(ui_configscreen);
lv_obj_set_width( ui_panelsetupbuttons, 480);
lv_obj_set_height( ui_panelsetupbuttons, 254);
lv_obj_set_x( ui_panelsetupbuttons, 0 );
lv_obj_set_y( ui_panelsetupbuttons, 66 );
lv_obj_set_align( ui_panelsetupbuttons, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_panelsetupbuttons,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_panelsetupbuttons, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelsetupbuttons, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelsetupbuttons, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelsetupbuttons, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelsetupbuttons, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelsetupbuttons, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelsetupbuttons, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttontracksetup = lv_button_create(ui_panelsetupbuttons);
lv_obj_set_width( ui_buttontracksetup, 250);
lv_obj_set_height( ui_buttontracksetup, 50);
lv_obj_set_align( ui_buttontracksetup, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_buttontracksetup,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_buttontracksetup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_set_ext_click_area(ui_buttontracksetup, 5);
lv_obj_add_flag( ui_buttontracksetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttontracksetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttontracksetup, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttontracksetup, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttontracksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttontracksetup, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttontracksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttontracksetup, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltracksetuptext = lv_label_create(ui_buttontracksetup);
lv_obj_set_width( ui_labeltracksetuptext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltracksetuptext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltracksetuptext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labeltracksetuptext,"TRACK SETUP");
lv_obj_set_style_text_color(ui_labeltracksetuptext, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltracksetuptext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltracksetuptext, &ui_font_BarlowCondensedBold32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltracksetup = lv_label_create(ui_buttontracksetup);
lv_obj_set_width( ui_labeltracksetup, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltracksetup, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltracksetup, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltracksetup,"");
lv_obj_set_style_text_color(ui_labeltracksetup, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltracksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltracksetup, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonstartsession = lv_button_create(ui_panelsetupbuttons);
lv_obj_set_width( ui_buttonstartsession, 250);
lv_obj_set_height( ui_buttonstartsession, 50);
lv_obj_set_align( ui_buttonstartsession, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_buttonstartsession,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_buttonstartsession, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_ext_click_area(ui_buttonstartsession, 5);
lv_obj_add_flag( ui_buttonstartsession, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonstartsession, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttonstartsession, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonstartsession, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonstartsession, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttonstartsession, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttonstartsession, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonstartsession, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelstartsession = lv_label_create(ui_buttonstartsession);
lv_obj_set_width( ui_labelstartsession, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelstartsession, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelstartsession, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labelstartsession,"START SESSION");
lv_obj_set_style_text_color(ui_labelstartsession, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelstartsession, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelstartsession, &ui_font_BarlowCondensedBold32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneldarklight = lv_obj_create(ui_panelsetupbuttons);
lv_obj_set_width( ui_paneldarklight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paneldarklight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_paneldarklight, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_paneldarklight,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_paneldarklight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_paneldarklight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneldarklight, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneldarklight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneldarklight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneldarklight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneldarklight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneldarklight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneldarklight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_paneldarklight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_paneldarklight, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttondark = lv_button_create(ui_paneldarklight);
lv_obj_set_width( ui_buttondark, 115);
lv_obj_set_height( ui_buttondark, 50);
lv_obj_set_align( ui_buttondark, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_buttondark,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_buttondark, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_ext_click_area(ui_buttondark, 5);
lv_obj_add_flag( ui_buttondark, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttondark, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttondark, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttondark, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttondark, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttondark, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttondark, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttondark, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltracksetuptext2 = lv_label_create(ui_buttondark);
lv_obj_set_width( ui_labeltracksetuptext2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltracksetuptext2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltracksetuptext2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labeltracksetuptext2,"DARK");
lv_obj_set_style_text_color(ui_labeltracksetuptext2, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltracksetuptext2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltracksetuptext2, &ui_font_BarlowCondensedBold32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttondark1 = lv_button_create(ui_paneldarklight);
lv_obj_set_width( ui_buttondark1, 115);
lv_obj_set_height( ui_buttondark1, 50);
lv_obj_set_align( ui_buttondark1, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_buttondark1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_buttondark1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_ext_click_area(ui_buttondark1, 5);
lv_obj_add_flag( ui_buttondark1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttondark1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttondark1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttondark1, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttondark1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttondark1, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttondark1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttondark1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltracksetuptext1 = lv_label_create(ui_buttondark1);
lv_obj_set_width( ui_labeltracksetuptext1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltracksetuptext1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltracksetuptext1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labeltracksetuptext1,"LIGHT");
lv_obj_set_style_text_color(ui_labeltracksetuptext1, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltracksetuptext1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltracksetuptext1, &ui_font_BarlowCondensedBold32, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_panelsetupback, ui_event_panelsetupback, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttontracksetup, ui_event_buttontracksetup, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonstartsession, ui_event_buttonstartsession, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttondark, ui_event_buttondark, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttondark1, ui_event_buttondark1, LV_EVENT_ALL, NULL);

}

void ui_configscreen_screen_destroy(void)
{
   if (ui_configscreen) lv_obj_del(ui_configscreen);

// NULL screen variables
ui_configscreen= NULL;
ui_panelsetup= NULL;
ui_panelsetupback= NULL;
ui_labelback= NULL;
ui_labelbacktext= NULL;
ui_labelsetup= NULL;
ui_panelsetupbuttons= NULL;
ui_buttontracksetup= NULL;
ui_labeltracksetuptext= NULL;
ui_labeltracksetup= NULL;
ui_buttonstartsession= NULL;
ui_labelstartsession= NULL;
ui_paneldarklight= NULL;
ui_buttondark= NULL;
ui_labeltracksetuptext2= NULL;
ui_buttondark1= NULL;
ui_labeltracksetuptext1= NULL;

}
