// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#ifndef UI_CONFIGSCREEN_H
#define UI_CONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_configscreen
extern void ui_configscreen_screen_init(void);
extern void ui_configscreen_screen_destroy(void);
extern lv_obj_t *ui_configscreen;
extern lv_obj_t *ui_panelsetup;
extern void ui_event_panelsetupback( lv_event_t * e);
extern lv_obj_t *ui_panelsetupback;
extern lv_obj_t *ui_labelback;
extern lv_obj_t *ui_labelbacktext;
extern lv_obj_t *ui_labelsetup;
extern lv_obj_t *ui_panelsetupbuttons;
extern void ui_event_buttontracksetup( lv_event_t * e);
extern lv_obj_t *ui_buttontracksetup;
extern lv_obj_t *ui_labeltracksetuptext;
extern lv_obj_t *ui_labeltracksetup;
extern void ui_event_buttonstartsession( lv_event_t * e);
extern lv_obj_t *ui_buttonstartsession;
extern lv_obj_t *ui_labelstartsession;
extern lv_obj_t *ui_paneldarklight;
extern void ui_event_buttondark( lv_event_t * e);
extern lv_obj_t *ui_buttondark;
extern lv_obj_t *ui_labeltracksetuptext2;
extern void ui_event_buttondark1( lv_event_t * e);
extern lv_obj_t *ui_buttondark1;
extern lv_obj_t *ui_labeltracksetuptext1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

