// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#include "../ui.h"

lv_obj_t *ui_dashboardscreen = NULL;lv_obj_t *ui_labelspeedlabel = NULL;lv_obj_t *ui_labelspeedvar = NULL;lv_obj_t *ui_labelspeedunit = NULL;lv_obj_t *ui_labellapnum = NULL;lv_obj_t *ui_labellapvar = NULL;lv_obj_t *ui_labellapbest = NULL;lv_obj_t *ui_paneldelta = NULL;lv_obj_t *ui_labelarrow = NULL;lv_obj_t *ui_labeldeltavar = NULL;lv_obj_t *ui_labeldeltas = NULL;lv_obj_t *ui_bargy = NULL;lv_obj_t *ui_labelbargy = NULL;lv_obj_t *ui_bargx = NULL;lv_obj_t *ui_labelgxvar = NULL;lv_obj_t *ui_labelgyvar = NULL;lv_obj_t *ui_panelrecording = NULL;lv_obj_t *ui_labelrecording = NULL;
// event funtions
void ui_event_labelspeedvar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_configscreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_configscreen_screen_init);
}
}

void ui_event_panelrecording( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      stopRecording( e );
}
}

// build funtions

void ui_dashboardscreen_screen_init(void)
{
ui_dashboardscreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_dashboardscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_dashboardscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dashboardscreen, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dashboardscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelspeedlabel = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labelspeedlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelspeedlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelspeedlabel, 14 );
lv_obj_set_y( ui_labelspeedlabel, 32 );
lv_label_set_text(ui_labelspeedlabel,"SPEED");
lv_obj_set_style_text_color(ui_labelspeedlabel, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelspeedlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelspeedlabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelspeedlabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelspeedlabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelspeedvar = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labelspeedvar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelspeedvar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelspeedvar, 14 );
lv_obj_set_y( ui_labelspeedvar, 60 );
lv_label_set_text(ui_labelspeedvar,"69");
lv_obj_add_flag( ui_labelspeedvar, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labelspeedvar, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelspeedvar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelspeedvar, &ui_font_BarlowCondensedBold200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelspeedunit = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labelspeedunit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelspeedunit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelspeedunit, 14 );
lv_obj_set_y( ui_labelspeedunit, 224 );
lv_label_set_text(ui_labelspeedunit,"km / h");
lv_obj_set_style_text_color(ui_labelspeedunit, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelspeedunit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelspeedunit, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelspeedunit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelspeedunit, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellapnum = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labellapnum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellapnum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labellapnum, -14 );
lv_obj_set_y( ui_labellapnum, 32 );
lv_obj_set_align( ui_labellapnum, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_labellapnum,"LAP 4");
lv_obj_set_style_text_color(ui_labellapnum, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellapnum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellapnum, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellapvar = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labellapvar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellapvar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labellapvar, -14 );
lv_obj_set_y( ui_labellapvar, 60 );
lv_obj_set_align( ui_labellapvar, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_labellapvar,"1:23.74");
lv_obj_set_style_text_color(ui_labellapvar, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellapvar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellapvar, &ui_font_BarlowCondensedBold60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellapbest = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labellapbest, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellapbest, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labellapbest, -15 );
lv_obj_set_y( ui_labellapbest, 113 );
lv_obj_set_align( ui_labellapbest, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_labellapbest,"BEST 1:23.32");
lv_obj_set_style_text_color(ui_labellapbest, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellapbest, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellapbest, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneldelta = lv_obj_create(ui_dashboardscreen);
lv_obj_set_width( ui_paneldelta, 182);
lv_obj_set_height( ui_paneldelta, 64);
lv_obj_set_x( ui_paneldelta, -14 );
lv_obj_set_y( ui_paneldelta, 142 );
lv_obj_set_align( ui_paneldelta, LV_ALIGN_TOP_RIGHT );
lv_obj_remove_flag( ui_paneldelta, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_paneldelta, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_paneldelta, lv_color_hex(0x3A0F10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneldelta, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_paneldelta, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_paneldelta, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneldelta, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneldelta, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneldelta, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneldelta, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneldelta, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelarrow = lv_label_create(ui_paneldelta);
lv_obj_set_width( ui_labelarrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelarrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelarrow, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labelarrow,"");
lv_obj_set_style_text_color(ui_labelarrow, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelarrow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelarrow, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeldeltavar = lv_label_create(ui_paneldelta);
lv_obj_set_width( ui_labeldeltavar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeldeltavar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labeldeltavar, -22 );
lv_obj_set_y( ui_labeldeltavar, 0 );
lv_obj_set_align( ui_labeldeltavar, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_labeldeltavar,"0.42");
lv_obj_set_style_text_color(ui_labeldeltavar, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeldeltavar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeldeltavar, &ui_font_BarlowCondensedBold60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeldeltas = lv_label_create(ui_paneldelta);
lv_obj_set_width( ui_labeldeltas, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeldeltas, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labeldeltas, -2 );
lv_obj_set_y( ui_labeldeltas, 8 );
lv_obj_set_align( ui_labeldeltas, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_labeldeltas,"S");
lv_obj_set_style_text_color(ui_labeldeltas, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeldeltas, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeldeltas, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bargy = lv_bar_create(ui_dashboardscreen);
lv_bar_set_mode(ui_bargy, LV_BAR_MODE_SYMMETRICAL);
lv_bar_set_range(ui_bargy, -300,300);
lv_bar_set_value(ui_bargy,40,LV_ANIM_OFF);
lv_bar_set_start_value(ui_bargy, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_bargy, 36);
lv_obj_set_height( ui_bargy, 220);
lv_obj_set_x( ui_bargy, 0 );
lv_obj_set_y( ui_bargy, 61 );
lv_obj_set_align( ui_bargy, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_bargy, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bargy, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bargy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_bargy, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_bargy, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_bargy, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_bargy, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_bargy, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bargy, lv_color_hex(0xFFD400), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bargy, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_bargy,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_bargy, lv_obj_get_style_pad_right(ui_bargy,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_labelbargy = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labelbargy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelbargy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelbargy, 0 );
lv_obj_set_y( ui_labelbargy, 42 );
lv_obj_set_align( ui_labelbargy, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_labelbargy,"G-Y");
lv_obj_set_style_text_color(ui_labelbargy, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelbargy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelbargy, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bargx = lv_bar_create(ui_dashboardscreen);
lv_bar_set_mode(ui_bargx, LV_BAR_MODE_SYMMETRICAL);
lv_bar_set_range(ui_bargx, -300,300);
lv_bar_set_value(ui_bargx,120,LV_ANIM_OFF);
lv_bar_set_start_value(ui_bargx, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_bargx, 480);
lv_obj_set_height( ui_bargx, 36);
lv_obj_set_align( ui_bargx, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_radius(ui_bargx, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bargx, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bargx, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_bargx, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_bargx, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_bargx, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_bargx, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_bargx, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bargx, lv_color_hex(0xFFD400), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bargx, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_bargx,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_bargx, lv_obj_get_style_pad_right(ui_bargx,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_labelgxvar = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labelgxvar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelgxvar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelgxvar, 14 );
lv_obj_set_y( ui_labelgxvar, -10 );
lv_obj_set_align( ui_labelgxvar, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_labelgxvar,"G-X 1.20");
lv_obj_set_style_text_color(ui_labelgxvar, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelgxvar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelgxvar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelgxvar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelgxvar, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelgyvar = lv_label_create(ui_dashboardscreen);
lv_obj_set_width( ui_labelgyvar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelgyvar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelgyvar, -14 );
lv_obj_set_y( ui_labelgyvar, -10 );
lv_obj_set_align( ui_labelgyvar, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_labelgyvar,"-0.40 G-Y");
lv_obj_set_style_text_color(ui_labelgyvar, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelgyvar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelgyvar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelgyvar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelgyvar, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelrecording = lv_obj_create(ui_dashboardscreen);
lv_obj_set_width( ui_panelrecording, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panelrecording, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panelrecording, 0 );
lv_obj_set_y( ui_panelrecording, -36 );
lv_obj_set_align( ui_panelrecording, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_panelrecording, 20);
lv_obj_add_flag( ui_panelrecording, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_panelrecording, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelrecording, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelrecording, lv_color_hex(0xFF3B3B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelrecording, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelrecording, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelrecording, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelrecording, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelrecording, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelrecording = lv_label_create(ui_panelrecording);
lv_obj_set_width( ui_labelrecording, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelrecording, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelrecording, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelrecording," REC");
lv_obj_set_style_text_color(ui_labelrecording, lv_color_hex(0x3A0F10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelrecording, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_labelspeedvar, ui_event_labelspeedvar, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panelrecording, ui_event_panelrecording, LV_EVENT_ALL, NULL);

}

void ui_dashboardscreen_screen_destroy(void)
{
   if (ui_dashboardscreen) lv_obj_del(ui_dashboardscreen);

// NULL screen variables
ui_dashboardscreen= NULL;
ui_labelspeedlabel= NULL;
ui_labelspeedvar= NULL;
ui_labelspeedunit= NULL;
ui_labellapnum= NULL;
ui_labellapvar= NULL;
ui_labellapbest= NULL;
ui_paneldelta= NULL;
ui_labelarrow= NULL;
ui_labeldeltavar= NULL;
ui_labeldeltas= NULL;
ui_bargy= NULL;
ui_labelbargy= NULL;
ui_bargx= NULL;
ui_labelgxvar= NULL;
ui_labelgyvar= NULL;
ui_panelrecording= NULL;
ui_labelrecording= NULL;

}
