// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#ifndef UI_DASHBOARDSCREEN_H
#define UI_DASHBOARDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dashboardscreen
extern void ui_dashboardscreen_screen_init(void);
extern void ui_dashboardscreen_screen_destroy(void);
extern lv_obj_t *ui_dashboardscreen;
extern lv_obj_t *ui_labelspeedlabel;
extern void ui_event_labelspeedvar( lv_event_t * e);
extern lv_obj_t *ui_labelspeedvar;
extern lv_obj_t *ui_labelspeedunit;
extern lv_obj_t *ui_labellapnum;
extern lv_obj_t *ui_labellapvar;
extern lv_obj_t *ui_labellapbest;
extern lv_obj_t *ui_paneldelta;
extern lv_obj_t *ui_labelarrow;
extern lv_obj_t *ui_labeldeltavar;
extern lv_obj_t *ui_labeldeltas;
extern lv_obj_t *ui_bargy;
extern lv_obj_t *ui_labelbargy;
extern lv_obj_t *ui_bargx;
extern lv_obj_t *ui_labelgxvar;
extern lv_obj_t *ui_labelgyvar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

