// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: KartDataDisplay

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Image_bg = NULL;lv_obj_t *ui_Label_speed = NULL;lv_obj_t *ui_speed1 = NULL;lv_obj_t *ui_speed2 = NULL;lv_obj_t *ui_speed3 = NULL;lv_obj_t *ui_speed4 = NULL;lv_obj_t *ui_speed5 = NULL;lv_obj_t *ui_speed6 = NULL;lv_obj_t *ui_speed7 = NULL;lv_obj_t *ui_speed8 = NULL;lv_obj_t *ui_speed9 = NULL;lv_obj_t *ui_speed10 = NULL;lv_obj_t *ui_Image_needle = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_bg = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image_bg, &ui_img_images_bg_png);
lv_obj_set_width( ui_Image_bg, LV_SIZE_CONTENT);  /// 6
lv_obj_set_height( ui_Image_bg, LV_SIZE_CONTENT);   /// 135
lv_obj_set_align( ui_Image_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_speed = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_speed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_speed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_speed, 0 );
lv_obj_set_y( ui_Label_speed, 113 );
lv_obj_set_align( ui_Label_speed, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_speed,"70");
lv_obj_set_style_text_color(ui_Label_speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_speed, &ui_font_DS36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speed1 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed1, &ui_img_1963053285);
lv_obj_set_width( ui_speed1, LV_SIZE_CONTENT);  /// 58
lv_obj_set_height( ui_speed1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_speed1, -196 );
lv_obj_set_y( ui_speed1, 111 );
lv_obj_set_align( ui_speed1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed2 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed2, &ui_img_1963050210);
lv_obj_set_width( ui_speed2, LV_SIZE_CONTENT);  /// 52
lv_obj_set_height( ui_speed2, LV_SIZE_CONTENT);   /// 52
lv_obj_set_x( ui_speed2, -162 );
lv_obj_set_y( ui_speed2, 71 );
lv_obj_set_align( ui_speed2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed3 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed3, &ui_img_1963051235);
lv_obj_set_width( ui_speed3, LV_SIZE_CONTENT);  /// 49
lv_obj_set_height( ui_speed3, LV_SIZE_CONTENT);   /// 55
lv_obj_set_x( ui_speed3, -130 );
lv_obj_set_y( ui_speed3, 30 );
lv_obj_set_align( ui_speed3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed4 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed4, &ui_img_1963047912);
lv_obj_set_width( ui_speed4, LV_SIZE_CONTENT);  /// 47
lv_obj_set_height( ui_speed4, LV_SIZE_CONTENT);   /// 62
lv_obj_set_x( ui_speed4, -96 );
lv_obj_set_y( ui_speed4, -9 );
lv_obj_set_align( ui_speed4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed5 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed5, &ui_img_1963048937);
lv_obj_set_width( ui_speed5, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_speed5, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_speed5, -52 );
lv_obj_set_y( ui_speed5, -30 );
lv_obj_set_align( ui_speed5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed6 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed6, &ui_img_1963045862);
lv_obj_set_width( ui_speed6, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_speed6, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_speed6, 1 );
lv_obj_set_y( ui_speed6, -30 );
lv_obj_set_align( ui_speed6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed7 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed7, &ui_img_1963046887);
lv_obj_set_width( ui_speed7, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_speed7, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_speed7, 48 );
lv_obj_set_y( ui_speed7, -30 );
lv_obj_set_align( ui_speed7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed8 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed8, &ui_img_1963060972);
lv_obj_set_width( ui_speed8, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_speed8, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_speed8, 96 );
lv_obj_set_y( ui_speed8, -30 );
lv_obj_set_align( ui_speed8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed9 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed9, &ui_img_1963061997);
lv_obj_set_width( ui_speed9, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_speed9, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_speed9, 143 );
lv_obj_set_y( ui_speed9, -30 );
lv_obj_set_align( ui_speed9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speed10 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_speed10, &ui_img_1524054327);
lv_obj_set_width( ui_speed10, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_speed10, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_speed10, 196 );
lv_obj_set_y( ui_speed10, -30 );
lv_obj_set_align( ui_speed10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_speed10, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_speed10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_needle = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image_needle, &ui_img_images_needle_png);
lv_obj_set_width( ui_Image_needle, LV_SIZE_CONTENT);  /// 8
lv_obj_set_height( ui_Image_needle, LV_SIZE_CONTENT);   /// 243
lv_obj_set_x( ui_Image_needle, 303 );
lv_obj_set_y( ui_Image_needle, 77 );
lv_obj_add_flag( ui_Image_needle, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image_needle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_pivot(ui_Image_needle,4,303);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Image_bg= NULL;
ui_Label_speed= NULL;
ui_speed1= NULL;
ui_speed2= NULL;
ui_speed3= NULL;
ui_speed4= NULL;
ui_speed5= NULL;
ui_speed6= NULL;
ui_speed7= NULL;
ui_speed8= NULL;
ui_speed9= NULL;
ui_speed10= NULL;
ui_Image_needle= NULL;

}
