// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: KartDataDisplay

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_bg;
extern lv_obj_t *ui_Label_speed;
extern lv_obj_t *ui_speed1;
extern lv_obj_t *ui_speed2;
extern lv_obj_t *ui_speed3;
extern lv_obj_t *ui_speed4;
extern lv_obj_t *ui_speed5;
extern lv_obj_t *ui_speed6;
extern lv_obj_t *ui_speed7;
extern lv_obj_t *ui_speed8;
extern lv_obj_t *ui_speed9;
extern lv_obj_t *ui_speed10;
extern lv_obj_t *ui_Image_needle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

