// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#include "../ui.h"

lv_obj_t *ui_statusbarscreen = NULL;lv_obj_t *ui_panelstatus = NULL;lv_obj_t *ui_panelhelmet = NULL;lv_obj_t *ui_labeliconhelmet = NULL;lv_obj_t *ui_labeltaghelmet = NULL;lv_obj_t *ui_labelvarhelmet = NULL;lv_obj_t *ui_paneldisplay = NULL;lv_obj_t *ui_labelicondisplay = NULL;lv_obj_t *ui_labeltagdisplay = NULL;lv_obj_t *ui_labelvardisplay = NULL;lv_obj_t *ui_panelgps = NULL;lv_obj_t *ui_labelicongps = NULL;lv_obj_t *ui_labeltaggps = NULL;lv_obj_t *ui_labelvargps = NULL;lv_obj_t *ui_panelesp = NULL;lv_obj_t *ui_labeliconesp = NULL;lv_obj_t *ui_labeltagesp = NULL;lv_obj_t *ui_labelvaresp = NULL;
// event funtions
void ui_event_panelstatus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_configscreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_configscreen_screen_init);
}
}

// build funtions

void ui_statusbarscreen_screen_init(void)
{
ui_statusbarscreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_statusbarscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_statusbarscreen, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_statusbarscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelstatus = lv_obj_create(ui_statusbarscreen);
lv_obj_set_width( ui_panelstatus, 480);
lv_obj_set_height( ui_panelstatus, 26);
lv_obj_set_align( ui_panelstatus, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_panelstatus,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelstatus, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelstatus, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_panelstatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelstatus, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelstatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelstatus, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelstatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelstatus, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_panelstatus, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelstatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelstatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelstatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelstatus, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelhelmet = lv_obj_create(ui_panelstatus);
lv_obj_set_width( ui_panelhelmet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panelhelmet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_panelhelmet, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelhelmet,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelhelmet, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelhelmet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelhelmet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelhelmet, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelhelmet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelhelmet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelhelmet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelhelmet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeliconhelmet = lv_label_create(ui_panelhelmet);
lv_obj_set_width( ui_labeliconhelmet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeliconhelmet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeliconhelmet, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeliconhelmet,"");
lv_obj_set_style_text_color(ui_labeliconhelmet, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeliconhelmet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeliconhelmet, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltaghelmet = lv_label_create(ui_panelhelmet);
lv_obj_set_width( ui_labeltaghelmet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltaghelmet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltaghelmet, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltaghelmet,"HLMT");
lv_obj_set_style_text_color(ui_labeltaghelmet, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltaghelmet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeltaghelmet, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeltaghelmet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltaghelmet, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelvarhelmet = lv_label_create(ui_panelhelmet);
lv_obj_set_width( ui_labelvarhelmet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelvarhelmet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelvarhelmet, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelvarhelmet,"--");
lv_obj_set_style_text_color(ui_labelvarhelmet, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelvarhelmet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelvarhelmet, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneldisplay = lv_obj_create(ui_panelstatus);
lv_obj_set_width( ui_paneldisplay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paneldisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_paneldisplay, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_paneldisplay,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_paneldisplay, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_paneldisplay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_paneldisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_paneldisplay, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneldisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneldisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_paneldisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_paneldisplay, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelicondisplay = lv_label_create(ui_paneldisplay);
lv_obj_set_width( ui_labelicondisplay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelicondisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelicondisplay, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelicondisplay,"");
lv_obj_set_style_text_color(ui_labelicondisplay, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelicondisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelicondisplay, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltagdisplay = lv_label_create(ui_paneldisplay);
lv_obj_set_width( ui_labeltagdisplay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltagdisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltagdisplay, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltagdisplay,"DISP");
lv_obj_set_style_text_color(ui_labeltagdisplay, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltagdisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeltagdisplay, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeltagdisplay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltagdisplay, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelvardisplay = lv_label_create(ui_paneldisplay);
lv_obj_set_width( ui_labelvardisplay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelvardisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelvardisplay, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelvardisplay,"--");
lv_obj_set_style_text_color(ui_labelvardisplay, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelvardisplay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelvardisplay, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelgps = lv_obj_create(ui_panelstatus);
lv_obj_set_width( ui_panelgps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panelgps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_panelgps, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelgps,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelgps, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelgps, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelgps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelgps, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelgps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelgps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelgps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelgps, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelicongps = lv_label_create(ui_panelgps);
lv_obj_set_width( ui_labelicongps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelicongps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelicongps, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelicongps,"");
lv_obj_set_style_text_color(ui_labelicongps, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelicongps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelicongps, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltaggps = lv_label_create(ui_panelgps);
lv_obj_set_width( ui_labeltaggps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltaggps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltaggps, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltaggps,"GPS");
lv_obj_set_style_text_color(ui_labeltaggps, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltaggps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeltaggps, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeltaggps, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltaggps, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelvargps = lv_label_create(ui_panelgps);
lv_obj_set_width( ui_labelvargps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelvargps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelvargps, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelvargps,"--");
lv_obj_set_style_text_color(ui_labelvargps, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelvargps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelvargps, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelesp = lv_obj_create(ui_panelstatus);
lv_obj_set_width( ui_panelesp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panelesp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_panelesp, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelesp,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelesp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelesp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelesp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelesp, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelesp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelesp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelesp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelesp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeliconesp = lv_label_create(ui_panelesp);
lv_obj_set_width( ui_labeliconesp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeliconesp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeliconesp, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeliconesp,"");
lv_obj_set_style_text_color(ui_labeliconesp, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeliconesp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeliconesp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltagesp = lv_label_create(ui_panelesp);
lv_obj_set_width( ui_labeltagesp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltagesp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltagesp, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltagesp,"ESP");
lv_obj_set_style_text_color(ui_labeltagesp, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltagesp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeltagesp, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeltagesp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltagesp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelvaresp = lv_label_create(ui_panelesp);
lv_obj_set_width( ui_labelvaresp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelvaresp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelvaresp, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelvaresp,"--");
lv_obj_set_style_text_color(ui_labelvaresp, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelvaresp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelvaresp, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_panelstatus, ui_event_panelstatus, LV_EVENT_ALL, NULL);

}

void ui_statusbarscreen_screen_destroy(void)
{
   if (ui_statusbarscreen) lv_obj_del(ui_statusbarscreen);

// NULL screen variables
ui_statusbarscreen= NULL;
ui_panelstatus= NULL;
ui_panelhelmet= NULL;
ui_labeliconhelmet= NULL;
ui_labeltaghelmet= NULL;
ui_labelvarhelmet= NULL;
ui_paneldisplay= NULL;
ui_labelicondisplay= NULL;
ui_labeltagdisplay= NULL;
ui_labelvardisplay= NULL;
ui_panelgps= NULL;
ui_labelicongps= NULL;
ui_labeltaggps= NULL;
ui_labelvargps= NULL;
ui_panelesp= NULL;
ui_labeliconesp= NULL;
ui_labeltagesp= NULL;
ui_labelvaresp= NULL;

}
