// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#ifndef UI_STATUSBARSCREEN_H
#define UI_STATUSBARSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_statusbarscreen
extern void ui_statusbarscreen_screen_init(void);
extern void ui_statusbarscreen_screen_destroy(void);
extern lv_obj_t *ui_statusbarscreen;
extern void ui_event_panelstatus( lv_event_t * e);
extern lv_obj_t *ui_panelstatus;
extern lv_obj_t *ui_panelhelmet;
extern lv_obj_t *ui_labeliconhelmet;
extern lv_obj_t *ui_labeltaghelmet;
extern lv_obj_t *ui_labelvarhelmet;
extern lv_obj_t *ui_paneldisplay;
extern lv_obj_t *ui_labelicondisplay;
extern lv_obj_t *ui_labeltagdisplay;
extern lv_obj_t *ui_labelvardisplay;
extern lv_obj_t *ui_panelgps;
extern lv_obj_t *ui_labelicongps;
extern lv_obj_t *ui_labeltaggps;
extern lv_obj_t *ui_labelvargps;
extern lv_obj_t *ui_panelesp;
extern lv_obj_t *ui_labeliconesp;
extern lv_obj_t *ui_labeltagesp;
extern lv_obj_t *ui_labelvaresp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

