// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: KartDataDisplay

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_bg;
extern lv_obj_t *ui_Label_speed;
extern lv_obj_t *ui_speed1;
extern lv_obj_t *ui_speed2;
extern lv_obj_t *ui_speed3;
extern lv_obj_t *ui_speed4;
extern lv_obj_t *ui_speed5;
extern lv_obj_t *ui_speed6;
extern lv_obj_t *ui_speed7;
extern lv_obj_t *ui_speed8;
extern lv_obj_t *ui_speed9;
extern lv_obj_t *ui_speed10;
extern lv_obj_t *ui_centerRed;
extern lv_obj_t *ui_centerYellow;
extern lv_obj_t *ui_centerGreen;
extern lv_obj_t *ui_LabesEspNow;
extern lv_obj_t *ui_centerLeftRed;
extern lv_obj_t *ui_centerLeftYellow;
extern lv_obj_t *ui_centerLeftGreen;
extern lv_obj_t *ui_LabelGpsCount;
extern lv_obj_t *ui_centerRightRed;
extern lv_obj_t *ui_centerRightYellow;
extern lv_obj_t *ui_centerRightGreen;
extern lv_obj_t *ui_LabelBattery;
extern lv_obj_t *ui_leftRed;
extern lv_obj_t *ui_gForce1;
extern lv_obj_t *ui_gForce2;
extern lv_obj_t *ui_gForce3;
extern lv_obj_t *ui_gForce4;
extern lv_obj_t *ui_gForce5;
extern lv_obj_t *ui_gForce6;
extern lv_obj_t *ui_gForce7;
extern lv_obj_t *ui_gForce8;
extern lv_obj_t *ui_gForce9;
extern lv_obj_t *ui_gForce10;
extern lv_obj_t *ui_gForce11;
extern lv_obj_t *ui_gForce12;
extern lv_obj_t *ui_gForce13;
extern lv_obj_t *ui_gForce14;
extern lv_obj_t *ui_gForce15;
extern lv_obj_t *ui_gForce16;
extern lv_obj_t *ui_gForce17;
extern lv_obj_t *ui_gForce18;
extern lv_obj_t *ui_gForce19;
extern lv_obj_t *ui_gForce20;
extern lv_obj_t *ui_Image_needle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

