// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#ifndef UI_TRACKSCREEN_H
#define UI_TRACKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_trackscreen
extern void ui_trackscreen_screen_init(void);
extern void ui_trackscreen_screen_destroy(void);
extern lv_obj_t *ui_trackscreen;
extern lv_obj_t *ui_paneltracksetup;
extern void ui_event_paneltracksetupback( lv_event_t * e);
extern lv_obj_t *ui_paneltracksetupback;
extern lv_obj_t *ui_labeltrackback;
extern lv_obj_t *ui_labeltrackbacktext;
extern lv_obj_t *ui_labeltracksetup1;
extern lv_obj_t *ui_paneldirty;
extern lv_obj_t *ui_dirtydot;
extern lv_obj_t *ui_labeldirtytext;
extern lv_obj_t *ui_panelbody;
extern lv_obj_t *ui_paneltrack;
extern lv_obj_t *ui_paneltrackheader;
extern lv_obj_t *ui_labeltrackheader;
extern lv_obj_t *ui_labeltrackpos;
extern lv_obj_t *ui_paneltrackstepper;
extern lv_obj_t *ui_panelstepper;
extern void ui_event_buttonstepperl( lv_event_t * e);
extern lv_obj_t *ui_buttonstepperl;
extern lv_obj_t *ui_labelstepperleft;
extern void ui_event_labelsteppertrackname( lv_event_t * e);
extern lv_obj_t *ui_labelsteppertrackname;
extern void ui_event_buttonstepperr( lv_event_t * e);
extern lv_obj_t *ui_buttonstepperr;
extern lv_obj_t *ui_labelstepperright;
extern void ui_event_buttonaddtrack( lv_event_t * e);
extern lv_obj_t *ui_buttonaddtrack;
extern lv_obj_t *ui_labeladdtrack;
extern lv_obj_t *ui_panelcoord;
extern lv_obj_t *ui_panelstartline;
extern lv_obj_t *ui_labelstartline;
extern lv_obj_t *ui_labelstartlinehint;
extern lv_obj_t *ui_panellinel;
extern lv_obj_t *ui_labeltagl;
extern void ui_event_labellatl( lv_event_t * e);
extern lv_obj_t *ui_labellatl;
extern void ui_event_labellonl( lv_event_t * e);
extern lv_obj_t *ui_labellonl;
extern void ui_event_labelemptyl( lv_event_t * e);
extern lv_obj_t *ui_labelemptyl;
extern void ui_event_buttonpinl( lv_event_t * e);
extern lv_obj_t *ui_buttonpinl;
extern lv_obj_t *ui_labelpinl;
extern lv_obj_t *ui_panelliner;
extern lv_obj_t *ui_labeltagr;
extern void ui_event_labellatr( lv_event_t * e);
extern lv_obj_t *ui_labellatr;
extern void ui_event_labellonr( lv_event_t * e);
extern lv_obj_t *ui_labellonr;
extern void ui_event_labelemptyr( lv_event_t * e);
extern lv_obj_t *ui_labelemptyr;
extern void ui_event_buttonpinr( lv_event_t * e);
extern lv_obj_t *ui_buttonpinr;
extern lv_obj_t *ui_labelpinr;
extern lv_obj_t *ui_panelactionbar;
extern void ui_event_buttoncancel( lv_event_t * e);
extern lv_obj_t *ui_buttoncancel;
extern lv_obj_t *ui_labelcancel;
extern void ui_event_buttonsave( lv_event_t * e);
extern lv_obj_t *ui_buttonsave;
extern lv_obj_t *ui_labelsave;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

