// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: minimalist

#include "../ui.h"

lv_obj_t *ui_trackscreen = NULL;lv_obj_t *ui_paneltracksetup = NULL;lv_obj_t *ui_paneltracksetupback = NULL;lv_obj_t *ui_labeltrackback = NULL;lv_obj_t *ui_labeltrackbacktext = NULL;lv_obj_t *ui_labeltracksetup1 = NULL;lv_obj_t *ui_paneldirty = NULL;lv_obj_t *ui_dirtydot = NULL;lv_obj_t *ui_labeldirtytext = NULL;lv_obj_t *ui_panelbody = NULL;lv_obj_t *ui_paneltrack = NULL;lv_obj_t *ui_paneltrackheader = NULL;lv_obj_t *ui_labeltrackheader = NULL;lv_obj_t *ui_labeltrackpos = NULL;lv_obj_t *ui_paneltrackstepper = NULL;lv_obj_t *ui_panelstepper = NULL;lv_obj_t *ui_buttonstepperl = NULL;lv_obj_t *ui_labelstepperleft = NULL;lv_obj_t *ui_labelsteppertrackname = NULL;lv_obj_t *ui_buttonstepperr = NULL;lv_obj_t *ui_labelstepperright = NULL;lv_obj_t *ui_buttonaddtrack = NULL;lv_obj_t *ui_labeladdtrack = NULL;lv_obj_t *ui_panelcoord = NULL;lv_obj_t *ui_panelstartline = NULL;lv_obj_t *ui_labelstartline = NULL;lv_obj_t *ui_labelstartlinehint = NULL;lv_obj_t *ui_panellinel = NULL;lv_obj_t *ui_labeltagl = NULL;lv_obj_t *ui_labellatl = NULL;lv_obj_t *ui_labellonl = NULL;lv_obj_t *ui_labelemptyl = NULL;lv_obj_t *ui_buttonpinl = NULL;lv_obj_t *ui_labelpinl = NULL;lv_obj_t *ui_panelliner = NULL;lv_obj_t *ui_labeltagr = NULL;lv_obj_t *ui_labellatr = NULL;lv_obj_t *ui_labellonr = NULL;lv_obj_t *ui_labelemptyr = NULL;lv_obj_t *ui_buttonpinr = NULL;lv_obj_t *ui_labelpinr = NULL;lv_obj_t *ui_panelactionbar = NULL;lv_obj_t *ui_buttoncancel = NULL;lv_obj_t *ui_labelcancel = NULL;lv_obj_t *ui_buttonsave = NULL;lv_obj_t *ui_labelsave = NULL;
// event funtions
void ui_event_paneltracksetupback( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_configscreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_configscreen_screen_init);
}
}

void ui_event_buttonstepperl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      previousTrackClicked( e );
}
}

void ui_event_labelsteppertrackname( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      trackNameClicked( e );
}
}

void ui_event_buttonstepperr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      nextTrackClicked( e );
}
}

void ui_event_buttonaddtrack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      addTrackClicked( e );
}
}

void ui_event_labellatl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      latLClicked( e );
}
}

void ui_event_labellonl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      lonLClicked( e );
}
}

void ui_event_labelemptyl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      emptyLClicked( e );
}
}

void ui_event_buttonpinl( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      startPinLClicked( e );
}
}

void ui_event_labellatr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      latRClicked( e );
}
}

void ui_event_labellonr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      lonRClicked( e );
}
}

void ui_event_labelemptyr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      emptyRClicked( e );
}
}

void ui_event_buttonpinr( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      startPinRClicked( e );
}
}

void ui_event_buttoncancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      cancelClicked( e );
}
}

void ui_event_buttonsave( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      saveClicked( e );
}
}

// build funtions

void ui_trackscreen_screen_init(void)
{
ui_trackscreen = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_trackscreen, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_trackscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneltracksetup = lv_obj_create(ui_trackscreen);
lv_obj_set_width( ui_paneltracksetup, 480);
lv_obj_set_height( ui_paneltracksetup, 40);
lv_obj_set_x( ui_paneltracksetup, 0 );
lv_obj_set_y( ui_paneltracksetup, 26 );
lv_obj_set_align( ui_paneltracksetup, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_paneltracksetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneltracksetup, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneltracksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_paneltracksetup, lv_color_hex(0x1A1D23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_paneltracksetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneltracksetup, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_paneltracksetup, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneltracksetupback = lv_obj_create(ui_paneltracksetup);
lv_obj_set_width( ui_paneltracksetupback, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paneltracksetupback, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_paneltracksetupback, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_paneltracksetupback,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_paneltracksetupback, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_ext_click_area(ui_paneltracksetupback, 10);
lv_obj_remove_flag( ui_paneltracksetupback, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneltracksetupback, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneltracksetupback, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneltracksetupback, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneltracksetupback, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneltracksetupback, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneltracksetupback, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneltracksetupback, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltrackback = lv_label_create(ui_paneltracksetupback);
lv_obj_set_width( ui_labeltrackback, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltrackback, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labeltrackback, 0 );
lv_obj_set_y( ui_labeltrackback, -1 );
lv_obj_set_align( ui_labeltrackback, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labeltrackback,"");
lv_obj_set_style_text_color(ui_labeltrackback, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltrackback, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltrackback, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltrackbacktext = lv_label_create(ui_paneltracksetupback);
lv_obj_set_width( ui_labeltrackbacktext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltrackbacktext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labeltrackbacktext, 20 );
lv_obj_set_y( ui_labeltrackbacktext, 0 );
lv_obj_set_align( ui_labeltrackbacktext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labeltrackbacktext,"SETUP");
lv_obj_set_style_text_color(ui_labeltrackbacktext, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltrackbacktext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeltrackbacktext, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeltrackbacktext, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltrackbacktext, &ui_font_BarlowCondensedBold22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltracksetup1 = lv_label_create(ui_paneltracksetup);
lv_obj_set_width( ui_labeltracksetup1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltracksetup1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labeltracksetup1, 0 );
lv_obj_set_y( ui_labeltracksetup1, 1 );
lv_obj_set_align( ui_labeltracksetup1, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltracksetup1,"TRACK SETUP");
lv_obj_set_style_text_color(ui_labeltracksetup1, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltracksetup1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeltracksetup1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeltracksetup1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltracksetup1, &ui_font_BarlowCondensedBold32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneldirty = lv_obj_create(ui_paneltracksetup);
lv_obj_set_width( ui_paneldirty, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_paneldirty, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_paneldirty, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_paneldirty,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_paneldirty, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_ext_click_area(ui_paneldirty, 10);
lv_obj_remove_flag( ui_paneldirty, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneldirty, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneldirty, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneldirty, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneldirty, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneldirty, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneldirty, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneldirty, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dirtydot = lv_obj_create(ui_paneldirty);
lv_obj_set_width( ui_dirtydot, 8);
lv_obj_set_height( ui_dirtydot, 8);
lv_obj_set_align( ui_dirtydot, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dirtydot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_dirtydot, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dirtydot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dirtydot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_dirtydot, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_dirtydot, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_dirtydot, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_dirtydot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeldirtytext = lv_label_create(ui_paneldirty);
lv_obj_set_width( ui_labeldirtytext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeldirtytext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labeldirtytext, 20 );
lv_obj_set_y( ui_labeldirtytext, 0 );
lv_obj_set_align( ui_labeldirtytext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_labeldirtytext,"SAVED");
lv_obj_set_style_text_color(ui_labeldirtytext, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeldirtytext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labeldirtytext, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labeldirtytext, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeldirtytext, &ui_font_BarlowCondensedBold22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelbody = lv_obj_create(ui_trackscreen);
lv_obj_set_height( ui_panelbody, 254);
lv_obj_set_width( ui_panelbody, lv_pct(100));
lv_obj_set_x( ui_panelbody, 0 );
lv_obj_set_y( ui_panelbody, 66 );
lv_obj_set_flex_flow(ui_panelbody,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_panelbody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_panelbody, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelbody, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelbody, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelbody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelbody, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelbody, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelbody, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelbody, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelbody, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelbody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneltrack = lv_obj_create(ui_panelbody);
lv_obj_set_width( ui_paneltrack, lv_pct(100));
lv_obj_set_height( ui_paneltrack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_paneltrack, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_paneltrack,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_paneltrack, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_paneltrack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneltrack, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneltrack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneltrack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneltrack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneltrack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneltrack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneltrack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_paneltrack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_paneltrack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneltrackheader = lv_obj_create(ui_paneltrack);
lv_obj_set_width( ui_paneltrackheader, lv_pct(100));
lv_obj_set_height( ui_paneltrackheader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_paneltrackheader, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_paneltrackheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_paneltrackheader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_paneltrackheader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneltrackheader, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneltrackheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneltrackheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneltrackheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneltrackheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneltrackheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneltrackheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltrackheader = lv_label_create(ui_paneltrackheader);
lv_obj_set_width( ui_labeltrackheader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltrackheader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltrackheader, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltrackheader,"TRACK");
lv_obj_set_style_text_color(ui_labeltrackheader, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltrackheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltrackheader, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltrackpos = lv_label_create(ui_paneltrackheader);
lv_obj_set_width( ui_labeltrackpos, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltrackpos, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltrackpos, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltrackpos,"0 / 0");
lv_obj_set_style_text_color(ui_labeltrackpos, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltrackpos, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltrackpos, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_paneltrackstepper = lv_obj_create(ui_paneltrack);
lv_obj_set_height( ui_paneltrackstepper, 38);
lv_obj_set_width( ui_paneltrackstepper, lv_pct(100));
lv_obj_set_align( ui_paneltrackstepper, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_paneltrackstepper,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_paneltrackstepper, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_paneltrackstepper, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_paneltrackstepper, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneltrackstepper, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_paneltrackstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_paneltrackstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_paneltrackstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_paneltrackstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_paneltrackstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_paneltrackstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_paneltrackstepper, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelstepper = lv_obj_create(ui_paneltrackstepper);
lv_obj_set_height( ui_panelstepper, 38);
lv_obj_set_width( ui_panelstepper, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_panelstepper, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelstepper,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelstepper, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelstepper, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelstepper, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelstepper, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelstepper, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelstepper, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelstepper, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelstepper, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelstepper, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonstepperl = lv_button_create(ui_panelstepper);
lv_obj_set_width( ui_buttonstepperl, 38);
lv_obj_set_height( ui_buttonstepperl, 36);
lv_obj_set_align( ui_buttonstepperl, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonstepperl, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonstepperl, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_buttonstepperl, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonstepperl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttonstepperl, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttonstepperl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonstepperl, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_buttonstepperl, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonstepperl, lv_color_hex(0x14181E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_buttonstepperl, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_labelstepperleft = lv_label_create(ui_buttonstepperl);
lv_obj_set_width( ui_labelstepperleft, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelstepperleft, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelstepperleft, LV_ALIGN_CENTER );
lv_obj_set_ext_click_area(ui_labelstepperleft, 10);
lv_label_set_text(ui_labelstepperleft,"");
lv_obj_set_style_text_color(ui_labelstepperleft, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelstepperleft, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelstepperleft, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelsteppertrackname = lv_label_create(ui_panelstepper);
lv_obj_set_width( ui_labelsteppertrackname, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelsteppertrackname, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelsteppertrackname, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_labelsteppertrackname,LV_LABEL_LONG_MODE_DOTS);
lv_label_set_text(ui_labelsteppertrackname,"NO TRACKS");
lv_obj_add_flag( ui_labelsteppertrackname, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labelsteppertrackname, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelsteppertrackname, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelsteppertrackname, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelsteppertrackname, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelsteppertrackname, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_labelsteppertrackname, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_labelsteppertrackname, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_labelsteppertrackname, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_labelsteppertrackname, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonstepperr = lv_button_create(ui_panelstepper);
lv_obj_set_width( ui_buttonstepperr, 38);
lv_obj_set_height( ui_buttonstepperr, 36);
lv_obj_set_align( ui_buttonstepperr, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonstepperr, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonstepperr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_buttonstepperr, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonstepperr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttonstepperr, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttonstepperr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonstepperr, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_buttonstepperr, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonstepperr, lv_color_hex(0x14181E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_buttonstepperr, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_labelstepperright = lv_label_create(ui_buttonstepperr);
lv_obj_set_width( ui_labelstepperright, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelstepperright, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelstepperright, LV_ALIGN_CENTER );
lv_obj_set_ext_click_area(ui_labelstepperright, 10);
lv_label_set_text(ui_labelstepperright,"");
lv_obj_set_style_text_color(ui_labelstepperright, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelstepperright, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelstepperright, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonaddtrack = lv_button_create(ui_paneltrackstepper);
lv_obj_set_width( ui_buttonaddtrack, 38);
lv_obj_set_height( ui_buttonaddtrack, 38);
lv_obj_set_align( ui_buttonaddtrack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonaddtrack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonaddtrack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttonaddtrack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonaddtrack, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonaddtrack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttonaddtrack, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttonaddtrack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonaddtrack, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeladdtrack = lv_label_create(ui_buttonaddtrack);
lv_obj_set_width( ui_labeladdtrack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeladdtrack, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeladdtrack, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeladdtrack,"+");
lv_obj_set_style_text_color(ui_labeladdtrack, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeladdtrack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeladdtrack, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelcoord = lv_obj_create(ui_panelbody);
lv_obj_set_width( ui_panelcoord, lv_pct(100));
lv_obj_set_height( ui_panelcoord, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_panelcoord, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelcoord,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_panelcoord, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_panelcoord, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelcoord, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelcoord, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelcoord, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelcoord, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelcoord, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelcoord, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelcoord, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelcoord, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelcoord, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelstartline = lv_obj_create(ui_panelcoord);
lv_obj_set_width( ui_panelstartline, lv_pct(100));
lv_obj_set_height( ui_panelstartline, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_panelstartline, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelstartline,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelstartline, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_panelstartline, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelstartline, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelstartline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelstartline, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelstartline, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelstartline, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelstartline, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelstartline, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelstartline = lv_label_create(ui_panelstartline);
lv_obj_set_width( ui_labelstartline, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelstartline, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelstartline, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelstartline,"START LINE");
lv_obj_set_style_text_color(ui_labelstartline, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelstartline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelstartlinehint = lv_label_create(ui_panelstartline);
lv_obj_set_width( ui_labelstartlinehint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelstartlinehint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelstartlinehint, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelstartlinehint,"tap PIN to capture from GPS");
lv_obj_set_style_text_color(ui_labelstartlinehint, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelstartlinehint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelstartlinehint, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panellinel = lv_obj_create(ui_panelcoord);
lv_obj_set_height( ui_panellinel, 32);
lv_obj_set_width( ui_panellinel, lv_pct(100));
lv_obj_set_align( ui_panellinel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panellinel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panellinel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panellinel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panellinel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panellinel, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panellinel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panellinel, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panellinel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panellinel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panellinel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panellinel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panellinel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panellinel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panellinel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panellinel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltagl = lv_label_create(ui_panellinel);
lv_obj_set_width( ui_labeltagl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltagl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltagl, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltagl,"L");
lv_obj_set_style_text_color(ui_labeltagl, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltagl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltagl, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellatl = lv_label_create(ui_panellinel);
lv_obj_set_width( ui_labellatl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellatl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labellatl, LV_ALIGN_CENTER );
lv_label_set_text(ui_labellatl,"");
lv_obj_add_flag( ui_labellatl, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labellatl, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellatl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellatl, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellonl = lv_label_create(ui_panellinel);
lv_obj_set_width( ui_labellonl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellonl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labellonl, LV_ALIGN_CENTER );
lv_label_set_text(ui_labellonl,"");
lv_obj_add_flag( ui_labellonl, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labellonl, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellonl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellonl, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelemptyl = lv_label_create(ui_panellinel);
lv_obj_set_width( ui_labelemptyl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelemptyl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelemptyl, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelemptyl,"-- not set --");
lv_obj_add_flag( ui_labelemptyl, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labelemptyl, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelemptyl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelemptyl, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonpinl = lv_button_create(ui_panellinel);
lv_obj_set_width( ui_buttonpinl, 64);
lv_obj_set_height( ui_buttonpinl, 24);
lv_obj_set_align( ui_buttonpinl, LV_ALIGN_CENTER );
lv_obj_set_ext_click_area(ui_buttonpinl, 5);
lv_obj_add_flag( ui_buttonpinl, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonpinl, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttonpinl, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonpinl, lv_color_hex(0x14181E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonpinl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttonpinl, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttonpinl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonpinl, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonpinl, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_buttonpinl, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_labelpinl = lv_label_create(ui_buttonpinl);
lv_obj_set_width( ui_labelpinl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelpinl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelpinl, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelpinl,"PIN");
lv_obj_set_style_text_color(ui_labelpinl, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelpinl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelpinl, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelpinl, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelpinl, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelliner = lv_obj_create(ui_panelcoord);
lv_obj_set_height( ui_panelliner, 32);
lv_obj_set_width( ui_panelliner, lv_pct(100));
lv_obj_set_align( ui_panelliner, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_panelliner,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelliner, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_panelliner, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelliner, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelliner, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelliner, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelliner, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelliner, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelliner, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelliner, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelliner, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelliner, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelliner, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelliner, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelliner, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labeltagr = lv_label_create(ui_panelliner);
lv_obj_set_width( ui_labeltagr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labeltagr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labeltagr, LV_ALIGN_CENTER );
lv_label_set_text(ui_labeltagr,"R");
lv_obj_set_style_text_color(ui_labeltagr, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labeltagr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labeltagr, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellatr = lv_label_create(ui_panelliner);
lv_obj_set_width( ui_labellatr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellatr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labellatr, LV_ALIGN_CENTER );
lv_label_set_text(ui_labellatr,"");
lv_obj_add_flag( ui_labellatr, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labellatr, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellatr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellatr, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labellonr = lv_label_create(ui_panelliner);
lv_obj_set_width( ui_labellonr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labellonr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labellonr, LV_ALIGN_CENTER );
lv_label_set_text(ui_labellonr,"");
lv_obj_add_flag( ui_labellonr, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labellonr, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labellonr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labellonr, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelemptyr = lv_label_create(ui_panelliner);
lv_obj_set_width( ui_labelemptyr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelemptyr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelemptyr, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelemptyr,"-- not set --");
lv_obj_add_flag( ui_labelemptyr, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_labelemptyr, lv_color_hex(0x6B7280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelemptyr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelemptyr, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonpinr = lv_button_create(ui_panelliner);
lv_obj_set_width( ui_buttonpinr, 64);
lv_obj_set_height( ui_buttonpinr, 24);
lv_obj_set_align( ui_buttonpinr, LV_ALIGN_CENTER );
lv_obj_set_ext_click_area(ui_buttonpinr, 5);
lv_obj_add_flag( ui_buttonpinr, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonpinr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttonpinr, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonpinr, lv_color_hex(0x14181E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonpinr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttonpinr, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttonpinr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonpinr, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonpinr, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_buttonpinr, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_labelpinr = lv_label_create(ui_buttonpinr);
lv_obj_set_width( ui_labelpinr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelpinr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelpinr, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelpinr,"PIN");
lv_obj_set_style_text_color(ui_labelpinr, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelpinr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelpinr, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelpinr, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelpinr, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelactionbar = lv_obj_create(ui_trackscreen);
lv_obj_set_width( ui_panelactionbar, 480);
lv_obj_set_height( ui_panelactionbar, 48);
lv_obj_set_x( ui_panelactionbar, 0 );
lv_obj_set_y( ui_panelactionbar, 272 );
lv_obj_set_flex_flow(ui_panelactionbar,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_panelactionbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_panelactionbar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelactionbar, lv_color_hex(0x050608), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelactionbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelactionbar, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelactionbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_panelactionbar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_panelactionbar, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_panelactionbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_panelactionbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_panelactionbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_panelactionbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_panelactionbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_panelactionbar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttoncancel = lv_button_create(ui_panelactionbar);
lv_obj_set_width( ui_buttoncancel, 0);
lv_obj_set_height( ui_buttoncancel, 48);
lv_obj_set_align( ui_buttoncancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttoncancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttoncancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttoncancel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttoncancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttoncancel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_buttoncancel, lv_color_hex(0x1C2026), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_buttoncancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttoncancel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_buttoncancel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttoncancel, lv_color_hex(0x14181E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_buttoncancel, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_labelcancel = lv_label_create(ui_buttoncancel);
lv_obj_set_width( ui_labelcancel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelcancel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelcancel, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelcancel,"CANCEL");
lv_obj_set_style_text_color(ui_labelcancel, lv_color_hex(0xF6F8FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelcancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelcancel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelcancel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelcancel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_buttonsave = lv_button_create(ui_panelactionbar);
lv_obj_set_width( ui_buttonsave, 0);
lv_obj_set_height( ui_buttonsave, 48);
lv_obj_set_align( ui_buttonsave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_buttonsave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_buttonsave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_buttonsave, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonsave, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_buttonsave, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_buttonsave, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_buttonsave, lv_color_hex(0x14181E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_buttonsave, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_labelsave = lv_label_create(ui_buttonsave);
lv_obj_set_width( ui_labelsave, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelsave, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelsave, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelsave,"SAVE");
lv_obj_set_style_text_color(ui_labelsave, lv_color_hex(0x0D1014), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_labelsave, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_labelsave, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_labelsave, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_labelsave, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_paneltracksetupback, ui_event_paneltracksetupback, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonstepperl, ui_event_buttonstepperl, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labelsteppertrackname, ui_event_labelsteppertrackname, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonstepperr, ui_event_buttonstepperr, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonaddtrack, ui_event_buttonaddtrack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labellatl, ui_event_labellatl, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labellonl, ui_event_labellonl, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labelemptyl, ui_event_labelemptyl, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonpinl, ui_event_buttonpinl, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labellatr, ui_event_labellatr, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labellonr, ui_event_labellonr, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_labelemptyr, ui_event_labelemptyr, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonpinr, ui_event_buttonpinr, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttoncancel, ui_event_buttoncancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonsave, ui_event_buttonsave, LV_EVENT_ALL, NULL);

}

void ui_trackscreen_screen_destroy(void)
{
   if (ui_trackscreen) lv_obj_del(ui_trackscreen);

// NULL screen variables
ui_trackscreen= NULL;
ui_paneltracksetup= NULL;
ui_paneltracksetupback= NULL;
ui_labeltrackback= NULL;
ui_labeltrackbacktext= NULL;
ui_labeltracksetup1= NULL;
ui_paneldirty= NULL;
ui_dirtydot= NULL;
ui_labeldirtytext= NULL;
ui_panelbody= NULL;
ui_paneltrack= NULL;
ui_paneltrackheader= NULL;
ui_labeltrackheader= NULL;
ui_labeltrackpos= NULL;
ui_paneltrackstepper= NULL;
ui_panelstepper= NULL;
ui_buttonstepperl= NULL;
ui_labelstepperleft= NULL;
ui_labelsteppertrackname= NULL;
ui_buttonstepperr= NULL;
ui_labelstepperright= NULL;
ui_buttonaddtrack= NULL;
ui_labeladdtrack= NULL;
ui_panelcoord= NULL;
ui_panelstartline= NULL;
ui_labelstartline= NULL;
ui_labelstartlinehint= NULL;
ui_panellinel= NULL;
ui_labeltagl= NULL;
ui_labellatl= NULL;
ui_labellonl= NULL;
ui_labelemptyl= NULL;
ui_buttonpinl= NULL;
ui_labelpinl= NULL;
ui_panelliner= NULL;
ui_labeltagr= NULL;
ui_labellatr= NULL;
ui_labellonr= NULL;
ui_labelemptyr= NULL;
ui_buttonpinr= NULL;
ui_labelpinr= NULL;
ui_panelactionbar= NULL;
ui_buttoncancel= NULL;
ui_labelcancel= NULL;
ui_buttonsave= NULL;
ui_labelsave= NULL;

}
